name: Publish to TestPyPI

on: 
  push:
    branches: [develop]

jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install pypa/build
        run:
          python -m pip install build toml --user

      - name: Build a binary wheel and a source tarball
        run: |
          python dev.py
          python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/